[versions]
kotlin = "2.3.0"

[libraries]
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
clikt = { group = "com.github.ajalt.clikt", name = "clikt", version = "5.0.3" }
lsp4j = { group = "org.eclipse.lsp4j", name = "org.eclipse.lsp4j", version = "0.24.0" }

[plugins]
